name: downscaling
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - asciitree==0.3.3
    - black==24.10.0
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cmocean==2.0
    - configmypy==0.1.0
    - contourpy==1.2.1
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - exceptiongroup==1.2.1
    - fasteners==0.19
    - filelock==3.14.0
    - flake8==7.1.1
    - fonttools==4.51.0
    - fsspec==2024.5.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h5py==3.7.0
    - huggingface-hub==0.23.1
    - idna==3.7
    - iniconfig==2.0.0
    - isort==5.13.2
    - jinja2==3.1.4
    - kiwisolver==1.4.5
    - lightning-utilities==0.11.2
    - markupsafe==2.1.5
    - matplotlib==3.6.3
    - mccabe==0.7.0
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nose==1.3.7
    - numcodecs==0.12.1
    - numpy==1.23.5
    - opencv-python==4.10.0.82
    - opt-einsum==3.3.0
    - packaging==24.0
    - pandas==1.4.4
    - pathspec==0.12.1
    - pillow==10.3.0
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - protobuf==4.25.3
    - psutil==5.9.8
    - pycodestyle==2.12.1
    - pyflakes==3.2.0
    - pyparsing==3.1.2
    - pytest==8.2.1
    - pytest-mock==3.14.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - requests==2.32.2
    - ruamel-yaml==0.18.6
    - ruamel-yaml-clib==0.2.8
    - scipy==1.13.1
    - sentry-sdk==2.3.1
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.12
    - tensorly==0.8.1
    - tensorly-torch==0.4.0
    - timm==0.6.13
    - tomli==2.0.1
    - torch==2.3.1
    - torch-harmonics==0.6.5
    - torchmetrics==1.4.0.post0
    - torchvision==0.18.1
    - tqdm==4.64.1
    - triton==2.3.1
    - typing-extensions==4.11.0
    - urllib3==2.2.1
    - wandb==0.17.0
    - zarr==2.18.1
